// Generated by the Maven Archetype Plug-in
package js_fb5.w_hs.de.testmavenapp.app;

import er.extensions.appserver.ERXSession;

public class Session extends ERXSession {
	private static final long serialVersionUID = 1L;

	public Session() {
		super();
	}
}
